name: img2webp & Deploy

# 在 Release 发布时 或 手动执行

on:
  release:
     types:
       - published

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/

      - name: Name
        run: |
          # 遍历指定目录中的每个文件
          for file in raw/*; do
          # 检查文件是否为普通文件（排除目录）
              if [ -f "$file" ]; then
              # 获取文件名（不包括路径）和扩展名
              filename=$(basename "$file")
              extension="${filename##*.}"
              filename_without_extension="${filename%.*}"
            
              # 使用mktemp生成一个新的随机文件名（不包含扩展名）
              new_name=$(mktemp -u XXXXXXXXXX)
            
              # 重建新的文件名，包括随机字符串和原始扩展名
              new_filename="${new_name}.${extension}"
              
              # 重命名文件，保留原始扩展名
              mv "$file" "raw/$new_filename"
              echo "Renamed $file to$new_filename"
            fi
          done
          
      # raw/ 作为原始图片存储，webp/ 作为压缩图片存储处，最后保存转换后的图片到 imgs/，可以自行修改为对应的文件夹位置
      # 安装相关插件，转换图片
      - name: Install & Convert
        run: |
          npm install -g webp-batch-convert@0.1.2
          # 要注意这里的版本号需要添加，如果不添加默认使用@Latest会出现问题
          cwebp-batch --in raw --out webp -q 75 -quiet
          #npx webp-batch-convert --in raw --out webp -q 75 -quiet
          mv webp/*.webp imgs/

      - name: Read package.json and bump version
        id: bump-version
        run: |
          # 读取package.json中的版本号
          version=$(cat package.json | grep -oP '"version": "\K[^"]+')
        
          # 解析版本号并增加
          IFS='.' read -ra VER <<< "$version"
          ((VER[2]++))
          new_version="${VER[0]}.${VER[1]}.${VER[2]}"
        
          # 更新package.json中的版本号
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$new_version\"/g" package.json
        
          # 输出新的版本号
          echo "Old version: $version"
          echo "New version: $new_version"

           # 删除 raw/ 和 webp/ 下的所有文件
      - name: Delete Files
        run: |
          rm -rf webp/*
          rm -rf raw/*
          touch webp/.keep
          touch raw/.keep

      # 获取文件名字
      - name: ls Files
        run:  |
          ls -R imgs/* > file.txt
          
      # 发布 NPM 包
      # 自行修改为自己的Github邮箱地址和用户名
      - name: Publish Package
        run: |
          git config --global user.email "3415645010@qq.com"
          git config --global user.name "jinghuashang"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Push
        run: |
          git add -A
          git commit -m "Publish"
          git push origin main
