name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/

      - name: Name
        run: |
          # 遍历指定目录中的每个文件
          for file in raw/*; do
          # 检查文件是否为普通文件（排除目录）
              if [ -f "$file" ]; then
              # 获取文件名（不包括路径）和扩展名
              filename=$(basename "$file")
              extension="${filename##*.}"
              filename_without_extension="${filename%.*}"
            
              # 使用mktemp生成一个新的随机文件名（不包含扩展名）
              new_name=$(mktemp -u XXXXXXXXXX)
            
              # 重建新的文件名，包括随机字符串和原始扩展名
              new_filename="${new_name}.${extension}"
              
              # 重命名文件，保留原始扩展名
              mv "$file" "raw/$new_filename"
              echo "Renamed $file to$new_filename"
            fi
          done
          
      # raw/ 作为原始图片存储，webp/ 作为压缩图片存储处，最后保存转换后的图片到 imgs/，可以自行修改为对应的文件夹位置
      # 安装相关插件，转换图片
      - name: Install & Convert
        run: |
          npm install -g webp-batch-convert@0.1.2
          # 要注意这里的版本号需要添加，如果不添加默认使用@Latest会出现问题
          cwebp-batch --in raw --out webp -q 75 -quiet
          #npx webp-batch-convert --in raw --out webp -q 75 -quiet
          mv webp/*.webp imgs/

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
     # 删除 raw/ 和 webp/ 下的所有文件
      - name: Delete Files
        run: |
          rm -rf webp/*
          rm -rf raw/*
          touch webp/.keep
          touch raw/.keep

      # 获取文件名字
      - name: ls Files
        run:  |
          ls -R imgs/* > file.txt

          
      - name: Push
        run: |
          git add -A
          git commit -m "Publish"
          git push origin main
